"""Updated user schema and model

Revision ID: 95474e6fd707
Revises: 8139cd53004f
Create Date: 2026-04-22 12:46:17.464438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '95474e6fd707'
down_revision: Union[str, Sequence[str], None] = '8139cd53004f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test5')
    op.add_column('user', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint(op.f('user_email_key'), 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_email_key'), 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('user', 'password')
    op.create_table('test5',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
