"""add role to user

Revision ID: deaab5d2ef4f
Revises: 2da0dcb82b7d
Create Date: 2026-04-23 21:32:49.685483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'deaab5d2ef4f'
down_revision: Union[str, Sequence[str], None] = '2da0dcb82b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE TYPE userrole AS ENUM ('ADMIN', 'USER')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole', create_type=False), nullable=False, server_default='USER'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.execute("DROP TYPE IF EXISTS userrole")
    # ### end Alembic commands ###
